### ISSUE TITLE
Bug: Unnecessary Code Block in the Transaction Component Page

### ISSUE THREAD

**Issue by jwkim960315** [coinbase/onchainkit#1005]
### Describe the bug and the steps to reproduce it

1. Go to onchain.xyz
2. Click on the "Docs" link located in the top navigation bar
3. In the sidebar, scroll down and select "Transaction"
4. Scroll down the page until you find the empty blue code block

### What's the expected behavior?

The code block shouldn't be there

**Comment by jwkim960315** [comment]
I found this very minor UI bug while navigating the docs page. Would love to fix this if I'm allowed to 🙂

**Comment by fakepixels** [comment]
Nice catch!

**Comment by jwkim960315** [comment]
@fakepixels Thanks for the quick fix! #1006
