### ISSUE TITLE
Feature Request: make type parameters use consistent lowerCamelCase

### ISSUE THREAD

**Issue by spennyp** [coinbase/onchainkit#102]
### Describe the solution you'd like

A nit, but currently type parameters mix snake_case and lowerCamelCase.

For example:

snake_case (post_url, refresh_period):
```ts
export type FrameMetadataType = {
    buttons?: [FrameButtonMetadata, ...FrameButtonMetadata[]];
    image: string;
    input?: FrameInputMetadata;
    post_url?: string;
    refresh_period?: number;
};
```

lowerCamelCase (isValid): 
```ts
export type FrameValidationResponse = {
    isValid: true;
    message: FrameValidationData;
} | {
    isValid: false;
    message: undefined;
};
```

Typescript generally uses lowerCamelCase here: 
* https://www.typescriptlang.org/docs/handbook/typescript-tooling-in-5-minutes.html#interfaces
* https://google.github.io/styleguide/tsguide.html#naming-rules-by-identifier-type

**Comment by Zizzamia** [comment]
Yeah, that's a big miss from my side! you right!

I wonder when we should do this breaking changes, if today or in a few weeks when things cool down.

@spennyp thoughts?

**Comment by spennyp** [comment]
Probably wait to bundle it with other breaking changes in a major release makes sense

**Comment by Zizzamia** [comment]
Yeah, right a lot of people are shipping some cool Frames, so I think this can be a nice breaking changes to do on Monday next week.

**Comment by Zizzamia** [comment]
@spennyp check `v0.5.3` https://github.com/coinbase/onchainkit/releases/tag/v0.5.3 
Has a couple of things you requested.
