### ISSUE TITLE
Documentation Request: Can't resolve 'viem/ens'

### ISSUE THREAD

**Issue by ackvf** [coinbase/onchainkit#104]
### Is your documentation request related to a problem? Please describe.

I just upgraded to latest onchainkit and get this error. It seems to me that this package should be added to the intsallation steps.

```
./node_modules/@coinbase/onchainkit/dist/lib/hooks/useAvatar.js:6:14
Module not found: Can't resolve 'viem/ens'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@coinbase/onchainkit/dist/lib/index.js
./src/app/(frame)/frame/page.tsx
```

**Comment by Zizzamia** [comment]
So we do have `peerDependencies` as 
```
"peerDependencies": {
    "react": "^18",
    "react-dom": "^18",
    "viem": "^2.7.0"
  },
```

But i wonder if we should convert `peerDependencies` directly into `dependencies`. 🤔

You are not the first person mentioning this, and I can see `peerDependencies` might cause some confusion.

@wespickett thoughts on this?

**Comment by cnasc** [comment]
At minimum we should indicate in docs, people probably see the install command and think it will work in any project without additional setup. I think the install command will call out unmet peer dependencies, but could be easy to miss depending on size of output

**Comment by Zizzamia** [comment]
But is it best at this point set them as `dependencies`, I guess I am wondering having this as `peerDependencies` is not really beneficial.

**Comment by cnasc** [comment]
`peerDependencies` is probably the most correct thing, to avoid having duplicate deps. However, there is an argument to be made in favor of just using `dependencies` to make the library "batteries included." IMO just adding a line saying "make sure peer dependencies are installed" to the docs would be sufficient but others might have different opinions.

**Comment by Zizzamia** [comment]
eheheh but people don't read docs 😅

**Comment by eragon512** [comment]
IMO adding peerDeps is something we can callout in our installation steps
as an example, wagmi does something similar for it's peerDeps: https://wagmi.sh/react/installation

maybe we can do something similar add the peerDeps in th install command section of our docs

**Comment by Zizzamia** [comment]
I kind of think we are overthinking this, if someone uses a library in the end they need those dependencies. So we just tell them, here the dependencies. Add a long list of thing someone should install feels odd too me and not simple enough.

**Comment by Zizzamia** [comment]
Let's get more opinions,
@robpolak @arsood what do you think? 

Btw @eragon512 your PR feels clean, so....

**Comment by robpolak** [comment]
Additionally, We might struggle to maintain compatibility across a large release set (e.g. can we guarantee our code will work across a major version of Viem)

**Comment by Zizzamia** [comment]
I will say let's go ahead with this
```
"dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "viem": "^2.7.0"
  },
```

After all this is the second time, already we got folks reaching out for confusion on the `peerDependencies` story in just a week.

**Comment by Zizzamia** [comment]
Actually, I think keeping the dependencies detach will help showcase how small is the bundlesize.

@ackvf sorry for the back end forward.
The answear to your question is, do
```
yarn add @coinbase/onchainkit viem@2.x react@18 react-dom@18
```
this will get you all the dependency you need.
