### ISSUE TITLE
Bug: Docs improperly set connectors on rainbowkit's getDefaultConfig

### ISSUE THREAD

**Issue by mykcryptodev** [coinbase/onchainkit#1076]
### Describe the bug and the steps to reproduce it

1. Go to [the wallet aggregator section](https://onchainkit.xyz/wallet/wallet#use-wallet-aggregator) of the docs

2. Notice how the getDefaultConfig is setting a "connectors" key:
![Screenshot 2024-08-15 at 7 21 15 PM](https://github.com/user-attachments/assets/7b4aecc1-3efb-437d-8ebb-46a96d1e80c8)

3. Connectors arent available as a key on the getDefaultConfig param:
```
Object literal may only specify known properties, and 'connectors' does not exist in type 'GetDefaultConfigParameters<[{ blockExplorers: { readonly default: { readonly name: "Basescan"; readonly url: "https://basescan.org"; readonly apiUrl: "https://api.basescan.org/api"; }; }; contracts: { readonly l2OutputOracle: { ...; }; ... 8 more ...; readonly l2ToL1MessagePasser: { ...; }; }; ... 9 more ...; serial...'.ts(2353)
```

### What's the expected behavior?

Use `createConfig` from wagmi to include the connectors like this:

```javascript
const connectors = connectorsForWallets( 
  [
    {
      groupName: 'Recommended Wallet',
      wallets: [coinbaseWallet],
    },
    {
      groupName: 'Other Wallets',
      wallets: [rainbowWallet, metaMaskWallet],
    },
  ],
  {
    appName: 'onchainkit',
    projectId: env.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID,
  },
);

const wagmiConfig = createConfig({
  chains: [base],
  multiInjectedProviderDiscovery: false,
  connectors,
  ssr: false,
  transports: {
    [base.id]: http(),
  },
});
```

requires importing { http, createConfig } from 'wagmi'

also, the props type is missing in the example:
```
type Props = {
  children: ReactNode;
};
```

**Comment by Zizzamia** [comment]
Great point, let me get this prioritized. cc @cpcramer

**Comment by cpcramer** [comment]
We have deprecated RainbowKit in favor of our new WalletModal
