### ISSUE TITLE
Bug: Hydration issue with wallet component

### ISSUE THREAD

**Issue by mykcryptodev** [coinbase/onchainkit#1077]
### Describe the bug and the steps to reproduce it

1. Create a standard Next.js project with the pages router using client side rendering
2. Follow [steps to put the wallet component](https://onchainkit.xyz/wallet/wallet#wallet-) anywhere on the page
3. Connect your wallet
4. Refresh the page

### What's the expected behavior?

Expecting no hydration issues when reloading

https://www.loom.com/share/e6a77177fc974dccb44438f0e1ae25d7

**Comment by Zizzamia** [comment]
A few quick question:
- what next version?
- is app or pages routing?
- are you using `use client`?

**Comment by mykcryptodev** [comment]
I am using
- "next": "^14.2.4"
- pages routing
- not using use client because I am using pages routing

**Comment by Zizzamia** [comment]
@abcrane123 fix this with `v0.30`
