### ISSUE TITLE
Feature Request: isBase should be made less misleading

### ISSUE THREAD

**Issue by mykcryptodev** [coinbase/onchainkit#1167]
### Describe the solution you'd like

This may be a personal preference thing but to me, Base is 8453... if I want to use a helper to detect if something "isBase", it should only return true if the chain is 8453.

Currently, isBase will [return true for Base Sepolia](https://github.com/coinbase/onchainkit/blob/a2afdc602517ed781798e6d86db8a29f02c8e1b9/src/isBase.ts#L10) as well.

Perhaps for backwards compatibility, there should be optional parameters passed like:
```typescript
isBase({ chainId, isMainnetOnly: true })
```

### Describe alternatives you've considered.

it's simple enough for me to make my own "isBaseMainnet" function:

```typescript
import { base } from "wagmi/chains";

const isBaseMainnet = ({ chainId }: { chainId: number }) => chainId === base.id;
```

but I feel like someone could stumble over "isBase" returning true for sepolia.

**Comment by Zizzamia** [comment]
Thank you @mykcryptodev, here a PR https://github.com/coinbase/onchainkit/pull/1221 with `isMainnetOnly` support.

The logic behind `isBase` is that we want something that helps us quickly to check a particular chain support. In particular for the CDP APIs, which are mostly bounded for now to Base or Base Sepolia.

I agree with you it can feel a bit confusing, and we specified the scope of the utility in the docs.

Happy to continue reflect on this in V1 if we see more adoption and confusion around this utility.
