### ISSUE TITLE
Feature Request: Swap Feature, display USD equivalent for token value

### ISSUE THREAD

**Issue by salparadi** [coinbase/onchainkit#1267]
### Describe the solution you'd like

Below the token amount, display the USD equivalent value of each token amount like Uniswap UI

### Describe alternatives you've considered.

Figure out how to hook into the token values myself and calculate independently, doesn't seem ideal :)

**Comment by fakepixels** [comment]
Great feedback. Thanks @salparadi - will revert back with a PR
