### ISSUE TITLE
Documentation Request: fix-doc-typo (Lifecycle Status)

### ISSUE THREAD

**Issue by DruxAMB** [coinbase/onchainkit#1284]
### Description
This pull request fixes a typo in the import statement in the documentation. The correct import statement should reference `LifeCycleStatus` instead of `LifecycleStatus`. **Twitter Handle:** [@druxamb](https://x.com/druxamb) [@baseworkshops](https://x.com/baseworkshops)

### Changes Made
- Updated the import statement in the documentation.
- Added the correct code snippet demonstrating the change.

### Original Code:
```
import type { LifecycleStatus } from '@coinbase/onchainkit/transaction';

const handleOnStatus = useCallback((status: LifecycleStatus) => {
  console.log('LifecycleStatus', status);
}, []);
```

### Updated Code:
```javascript
import { Transaction, type LifeCycleStatus } from '@coinbase/onchainkit/transaction';

const handleOnStatus = useCallback((status: LifeCycleStatus) => {
  console.log('LifecycleStatus', status);
}, []);

**Comment by mykcryptodev** [comment]
[This commit](https://github.com/coinbase/onchainkit/commit/90cf8ee90af7040ede6f276d2be32bdc3950e6cf) updates LifeCycleStatus to LifecycleStatus

Try bumping your onchainkit version and let me know if that solves the issue!

**Comment by DruxAMB** [comment]
oh, alright thanks. I was able to solve the issue by updating to the latest version @coinbase/onchainkit!!
