### ISSUE TITLE
Bug: Swap has various accessibility issues

### ISSUE THREAD

**Issue by samcartersmith** [coinbase/onchainkit#1290]
### Describe the bug and the steps to reproduce it

1. Go to https://onchainkit.xyz/#swap
2. Tab around the Swap component
3. Turn on a screen reader
4. Experience button labels with a screen reader

**Issues**
- The drop-down for selecting asset type have a confusing label and do not communicate name, state, or value
- The swap direction icon has no label
- There is no keyboard focus on the drop-down
- Dropdown asset selectors should function like select HTML components
- Red is used to indicate an error which is not clear to all users

Asset Selector
<img width="1601" alt="Screenshot 2024-09-24 at 10 00 16 AM" src="https://github.com/user-attachments/assets/977c6ff7-4c47-4aad-b333-10ba77d14475">

Swap Direction Button
<img width="1194" alt="Screenshot 2024-09-24 at 10 00 02 AM" src="https://github.com/user-attachments/assets/c4549e0f-477c-4770-98e1-92078151f3db">

### What's the expected behavior?

**Suggested Fixes**
- The drop-down for selecting asset type has a confusing label and do not communicate name, state, or value
You can use this spec as an example. https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/. When the user focuses the asset selector they should hear the following: purpose, value, and role. For example, "asset selector, ETH, combobox".
- The swap direction icon has no label
Use an aria-label on the button. For example, aria-label="change swap direction"
- There is no visual keyboard focus on the drop-down
Use an outline to indicate focus that meets a 3:1 contrast ratio or above.
- Visual focus indicators are not easy to see
Use an outline that meets a 3:1 or above contrast ratio.

**Comment by fakepixels** [comment]
Thanks so much for the detailed write up @samcartersmith 

We're looking into it! 🫡
