### ISSUE TITLE
Feature Request: Add additional context for the App Template

### ISSUE THREAD

**Issue by reva-jariwala2** [coinbase/onchainkit#1376]
### Describe the solution you'd like

Users could not understand what the app template was showing at first and what they were seeing on the page. They also did not realize that it was an NFT that they were transacting for - I would further clarify after.... We could add more context on the dev docs for it? May be helpful. I also think this could be another helpful app template: https://x.com/fkpxls/status/1841829742431133868

**Comment by mindapivessa** [comment]
Addressed with [the new quickstart app template](https://onchainkit.xyz/getting-started) and [on the Commerce template](https://onchain-commerce-template.vercel.app/).
