### ISSUE TITLE
Documentation Request: Documentations for @coinbase/onchainkit/styles.css 

### ISSUE THREAD

**Issue by wheval** [coinbase/onchainkit#1457]
### Is your documentation request related to a problem? Please describe.

So it is easier to debug your css code, because i was faced with CSS specificity issues.

**Comment by harshit-2004** [comment]
@wheval changed the css import path here #1659

**Comment by cpcramer** [comment]
We've added additional documentation + theming support! https://onchainkit.xyz/guides/themes

**Comment by wheval** [comment]
Thank you. @cpcramer 🫡
