### ISSUE TITLE
Feature Request: Adding testnet support for `<Checkout />` and `<Swap />` components

### ISSUE THREAD

**Issue by Ricy137** [coinbase/onchainkit#1635]
### Describe the solution you'd like

The developer experience of `<Checkout />` and `<Swap />` components are good and they both provide compatibility for more advanced operations. However, the two components only work on the mainnet and it would provide a better DX if there's an method to test these two components without costing real money. 

### Describe alternatives you've considered.

Adding testnet support for `Checkout />` and `<Swap />` components.

**Comment by fakepixels** [comment]
Acknowledged! Thanks @Ricy137. 

We recommend testing Swap with a very tiny amount of ETH, as there's no liquidity on Testnet for swap, so it's difficult to test that way. 

Will revert what's possible for <Checkout/> thank you!
