### ISSUE TITLE
Bug: Broken Farcaster Social Link 

### ISSUE THREAD

**Issue by mykcryptodev** [coinbase/onchainkit#1661]
### Describe the bug and the steps to reproduce it

1. Go to [this app](https://superbowl-onchain.vercel.app/contest/1)
2. Tap on one of the boxes that I own (myk.eth, same avatar as you see here in my gh profile)
3. Tap on the farcaster link generated by the `<Socials>` component

### What's the expected behavior?

Expect to go to a farcaster client like https://warpcast.com/myk

In actuality, the current app is what the user is linked to
<img width="697" alt="Screenshot 2024-11-24 at 1 50 35 PM" src="https://github.com/user-attachments/assets/71104606-a817-439b-834f-3acef6598c53">

Code for the app is [here](https://github.com/mykcryptodev/nft-boxes/blob/main/src/components/Identity/Owner.tsx#L112-L115)

### What version of the libraries are you using?

0.35.3

**Comment by fakepixels** [comment]
cc @cpcramer

**Comment by cpcramer** [comment]
Here is the fix https://github.com/coinbase/onchainkit/pull/1688! 

Will be included in the `v0.35.9` OCK release!

**Comment by cpcramer** [comment]
Here is the fix https://github.com/coinbase/onchainkit/pull/1688!

Will be included in the v0.35.9 OCK release!
