### ISSUE TITLE
Bug: VITE page: import {AppProviders} from 'src/AppProviders.tsx'

### ISSUE THREAD

**Issue by fawaz-exe** [coinbase/onchainkit#1699]
### Describe the bug and the steps to reproduce it

Go to: https://onchainkit.xyz/installation/vite#wrap-your-app-with-appproviders-
Line 1: import {AppProviders} from 'src/AppProviders.tsx'

### What's the expected behavior?

It should be`import 'Providers' from 'src/Providers.tsx'`

### What version of the libraries are you using?

- OnChainKit 0.35.8*

**Comment by cpcramer** [comment]
Fixed. Thanks!
