### ISSUE TITLE
Feature Request: Ability to use two postUrls in one frame for every button

### ISSUE THREAD

**Issue by svgvr8** [coinbase/onchainkit#196]
### Problem/Request

I get error 404 when I use "`action: post`" in more than one button. like this:

```	
{
			label: 'button one!',
			action: 'post',

		},
{
			label: 'button two!',
			action: 'post',

		}
```
### Alternatives

This feature works fine if used in frames.js but not on OnChainKit : https://github.com/limone-eth/slides-frame

**Comment by Zizzamia** [comment]
Ciao @svgvr8, can you share more on how your code is setup please.

**Comment by Zizzamia** [comment]
Closing this as lack of reply.
