### ISSUE TITLE
Bug: `getFrameMessage` throws `FetchError` when message is not valid

### ISSUE THREAD

**Issue by cnasc** [coinbase/onchainkit#236]
### Describe the bug and the steps to reproduce it

1. Send unsigned message to frame (can do this with `framegear`, just don't have `allowFramegear` property set)
2. See in console `⨯ FetchError: non-200 status returned from neynar : 400`
3. Cannot use `isValid` to send error state because of runtime error

### What's the expected behavior?

This failure should be handled in `getFrameMessage` so that `isValid` is false when this occurs. That will allow us to send customized error states.

### What version of the libraries are you using?

`"@coinbase/onchainkit": "0.10.0"`

**Comment by ktarun1419** [comment]
Hi @cnasc  can i work on this issue ?

**Comment by cnasc** [comment]
@ktarun1419 feel free!

**Comment by Zizzamia** [comment]
@ktarun1419 Niiiiice!

**Comment by Charlieste** [comment]
Hey guys! Just wondering if anyone is able to get around this?

**Comment by claudioantonio** [comment]
I think this issue relates to https://github.com/Zizzamia/a-frame-in-100-lines/issues/17

**Comment by cpcramer** [comment]
Frames have been deprecated.
