### ISSUE TITLE
Bug: Either `postUrl` or `getFrameHtmlResponse` not returning anything

### ISSUE THREAD

**Issue by mubarakone** [coinbase/onchainkit#240]
### Describe the bug and the steps to reproduce it

Below is my `api/frame/route.ts` file...
```
'use client'
import { FrameRequest, getFrameMessage, getFrameHtmlResponse } from '@coinbase/onchainkit';
import { NextRequest, NextResponse } from 'next/server';
import { useState } from 'react';

const [frameID, setFrameID] = useState(0)

async function getResponse(req: NextRequest): Promise<NextResponse> {
  const body: FrameRequest = await req.json();
  const { isValid, message } = await getFrameMessage(body);

  if (isValid) {
    if (message?.button === 1) {
        setFrameID(frameID - 1);
    }
    
    if (message?.button === 3) {
        setFrameID(frameID + 1);
    }
  }

  return new NextResponse(
    getFrameHtmlResponse({
      buttons: [
        {
          action: 'post',
          label: '⬅️ Back',
        },
        {
          label: `${frameID}/6`,
        },
        {
          action: 'post',
          label: 'Next ➡️',
        },
      ],
      image: {
        src: `http://localhost:3000/park-3.png`,
        aspectRatio: '1:1',
      },
      postUrl: `http://localhost:3000/api/frame`,
    }),
  );
}

export async function POST(req: NextRequest): Promise<Response> {
  return getResponse(req);
}

export const dynamic = 'force-dynamic';
```

### What's the expected behavior?

On framegear, the FrameMetadata and the initial frame loads just fine. When I click the 3rd button, `postUrl` is suppose to route to the API page and call `getFrameHtmlResponse`. But instead, framegear gives me errors:

![image](https://github.com/coinbase/onchainkit/assets/52806204/ae9e02a9-4ad7-4578-9c8a-bd797ea1be13)

### What version of the libraries are you using?

`"@coinbase/onchainkit": "^0.10.1",`

**Comment by cnasc** [comment]
👋 hi @mubarakone, looks you haven't set the `allowFramegear` option in `getFrameMessage` (see: https://onchainkit.xyz/frame/framegear#security-tip). Without that option set, your frame won't recognize `framegear` actions as valid. This is something we should try to provide a better error message for.

**Comment by mubarakone** [comment]
> 👋 hi @mubarakone, looks you haven't set the `allowFramegear` option in `getFrameMessage` (see: https://onchainkit.xyz/frame/framegear#security-tip). Without that option set, your frame won't recognize `framegear` actions as valid. This is something we should try to provide a better error message for.

Didn't work for me unfortunately 😢

**Comment by mubarakone** [comment]
FYI: I have the FrameMetadata generated based on a specific page on my application, since I want the end user to be redirected to that page, rather than the home page. Not sure if that is interfering with anything, just giving a heads up.

**Comment by cnasc** [comment]
Is your frame code publicly accessible? Can try to take a look on my end and see what we're running into.

Otherwise a few steps that might help:
- double check the postUrl in the initial frame FrameMetadata
- add some logging in your API handler (e.g., before and after the `isValid` -- is your route getting called, what is the value for `isValid`)

**Comment by mubarakone** [comment]
I fixed it now, it was a react issue. No fault on your end.
