### ISSUE TITLE
How To: How do I retrieve the frame URL 

### ISSUE THREAD

**Issue by mubarakone** [coinbase/onchainkit#254]
### Describe the bug and the steps to reproduce it

I tried to retrieve the frame URL using:
```
 if (isValid) {
    const frameURL = message.raw.action.url
    console.log('frameURL is: ', frameURL)
```
But it returns undefined:

```
frameURL is:  undefined
```

What is the correct way, or is it even possible?

### What's the expected behavior?

```
frameURL is: http://localhost:3000/PROJECT_FOLDER/FRAME_FOLDER/FRAME_PAGE
```

### What version of the libraries are you using?

`"@coinbase/onchainkit": "^0.10.1",`

**Comment by Zizzamia** [comment]
Are you testing this using Framegear? Ideally your goal it know the Frame you are so you can decide what to do.

Also have you tested in some way with a deployed Frame? Mostly I wonder if this is something we miss mocking on Framegear and how does behave in reality. cc @cnasc 

Have you thought to use State instead?

**Comment by cnasc** [comment]
Yeah this is likely something we need to populate when testing against a local frame
