### ISSUE TITLE
Add linting to `onchainkit`

### ISSUE THREAD

**Issue by kyhyco** [coinbase/onchainkit#260]
### Describe the solution you'd like

We should add eslint, biome, etc. to lint our code. Any preference?

**Comment by Zizzamia** [comment]
Be more specific, `eslint` is already present in the `src` folder.

**Comment by kyhyco** [comment]
Ah.. looks like `eslint` is only added to `framegear`. Will add it `src` and `site`

**Comment by roushou** [comment]
I think this issue can be closed since this PR https://github.com/coinbase/onchainkit/pull/497 has been merged @kyhyco @Zizzamia

**Comment by kyhyco** [comment]
Yup you are right! Thank you so much @roushou!
