### ISSUE TITLE
Bug: Warpcast Frame Tool not reflecting Framegear results during production.

### ISSUE THREAD

**Issue by mubarakone** [coinbase/onchainkit#263]
### Describe the bug and the steps to reproduce it

After testing the frames on framegear during development, I then pushed to production successfully. I then used the production URL to test the frame using Warpcast Frame Tool, and something doesn't seem quite right...

![image](https://github.com/coinbase/onchainkit/assets/52806204/39fd88c2-a492-424c-9c7f-54e274f0d90b)

The Frame successfully loads with the properties defined. However, the frame image is suppose to be a PNG image file located in the `/public` directory of my project. When pushed for production, I figured it would simply recognize the PNG image file I pointed to:

```
return new NextResponse(
        getFrameHtmlResponse({
            buttons: [
                {
                  label: ' ',
                },
                {
                  label: `${frameID}/6`,
                },
                {
                  action: 'post',
                  label: 'Preview ↪️',
                },
              ],
              image: {
                // Image is located in the /public directory. Works perfectly during development (with localhost domain of course)
                src: `https://newspaper.tips/first-frame-article.png`,
                aspectRatio: '1:1',
              },
              postUrl: `https://newspaper.tips/api/frame`,
        }),
      );
```

Below is a screenshot of `first-frame-article.png` found in the source files in Vercel:

![image](https://github.com/coinbase/onchainkit/assets/52806204/bd52ccb1-44aa-4cc7-b2da-5e14e9446aaf)

### What's the expected behavior?

Below is a screenshot of the images in `/public` directory working during development using framegear:
(This is actually `last-frame-article.png`, but both images are located in the same folder)

![image](https://github.com/coinbase/onchainkit/assets/52806204/921be27e-a191-48da-8daa-202d5e50818b)

### What version of the libraries are you using?

`"@coinbase/onchainkit": "^0.10.1",`
`"next": "latest",`
`
"react": "18.2.0", "react-dom": "18.2.0",
`
`"typescript": "^5.1.3",`

**Comment by Zizzamia** [comment]
@mubarakone love all the details, thank you for taking the time to write those down.

Quick question, what's the Frame production link? Would love to test a few things, and see what's going on.

**Comment by mubarakone** [comment]
https://newspaper.tips/latest/blog/release-of-tailwind-nextjs-starter-blog-v2.0

**Comment by mubarakone** [comment]
Maybe `fc:frame:image` does not accept images from the file system, at least during production. I think I have to store in a separate database, then fetch that URL to the image property. Here is an example of someone using Google Cloud to fetch the image:

Notice `storage.googleapis.com`, then scroll up the page and compare with mine `localhost`
![image](https://github.com/coinbase/onchainkit/assets/52806204/719a5c38-6d59-4fe0-93cd-5f219466df0d)

**Comment by mubarakone** [comment]
I also realized my `post_url` is still localhost, which is confusing because you can see my code snippet provided, it points to my production url. Not sure what is going on there

**Comment by Zizzamia** [comment]
Oh yeah
```
<meta name="fc:frame:image" content="http://localhost:3000/first-frame-article.png">
<meta name="fc:frame:post_url" content="http://localhost:3000/api/generateFrames">
```

When you set your initial metadata, how is the code setup? I think you have a ENV variable that is wrongly set between localhost and production.

like you need something
```
postUrl: `${NEXT_PUBLIC_URL}/api/frame`,
```

and `NEXT_PUBLIC_URL` should be set as 
```
export const NEXT_PUBLIC_URL =
  process.env.NODE_ENV == 'development' ? 'http://localhost:3000' : 'https://zizzamia.xyz';
```

**Comment by mubarakone** [comment]
I actually I didn't set up any ENV variables (except for OpenAI and Dynamic) Too lazy, so I just manually change it. Here is the entire file:
https://github.com/mubarakone/tailwind-css-starter-blog/blob/main/app/api/frame/route.ts

\api\frame\route.ts
```
import { FrameRequest, getFrameMessage, getFrameHtmlResponse } from '@coinbase/onchainkit';
import { NextRequest, NextResponse } from 'next/server';

let frameID = 0;
let firstFrameCalled = false

async function getResponse(req: NextRequest): Promise<NextResponse> {
  const body: FrameRequest = await req.json();
  const { isValid, message } = await getFrameMessage(body, {allowFramegear: true});

  if (isValid) {
    if (message?.button === 1) {
        frameID--;
    }
    
    if (message?.button === 3) {
        frameID++;
    }
  }

  if (firstFrameCalled) {
    if (frameID === 0) {
        return new NextResponse(
            getFrameHtmlResponse({
                buttons: [
                    {
                      label: ' ',
                    },
                    {
                      label: `${frameID}/6`,
                    },
                    {
                      action: 'post',
                      label: 'Preview ↪️',
                    },
                  ],
                  image: {
                    // Image is located in the public directory. Works perfectly during development (with localhost domain of course)
                    src: `https://newspaper.tips/first-frame-article.png`,
                    aspectRatio: '1:1',
                  },
                  postUrl: `https://newspaper.tips/api/frame`,
            }),
          );
      }
    
      if (frameID === 7) {
        return new NextResponse(
            getFrameHtmlResponse({
              buttons: [
                {
                  action: 'post',
                  label: '⬅️ Back',
                },
                {
                  label: `${frameID}/6`,
                },
                {
                  action: 'link',
                  label: 'Continue Reading 📖',
                  target: 'https://newspaper.tips/latest/blog/release-of-tailwind-nextjs-starter-blog-v2.0'
                },
              ],
              image: {
                src: `https://newspaper.tips/last-frame-article.png`,
                aspectRatio: '1:1',
              },
              postUrl: `https://newspaper.tips/api/frame`,
            }),
          );
      }
    
      if (frameID !== 0) {
        return new NextResponse(
            getFrameHtmlResponse({
              buttons: [
                {
                  action: 'post',
                  label: '⬅️ Back',
                },
                {
                  label: `${frameID}/6`,
                },
                {
                  action: 'post',
                  label: 'Next ➡️',
                },
              ],
              image: {
                src: `https://newspaper.tips/generated_images/snippet_${frameID - 1}.png`,
                aspectRatio: '1:1',
              },
              postUrl: `https://newspaper.tips/api/frame`,
            }),
          );
      }
  }

  firstFrameCalled = true;

  return new NextResponse(
    getFrameHtmlResponse({
      buttons: [
        {
          action: 'post',
          label: '⬅️ Back',
        },
        {
          label: `${frameID}/6`,
        },
        {
          action: 'post',
          label: 'Next ➡️',
        },
      ],
      image: {
        src: `https://newspaper.tips/generated_images/snippet_${frameID - 1}.png`,
        aspectRatio: '1:1',
      },
      postUrl: `https://newspaper.tips/api/generateFrames`,
    }),
  );
}

export async function POST(req: NextRequest): Promise<Response> {
  return getResponse(req);
}

export const dynamic = 'force-dynamic';
```

**Comment by mubarakone** [comment]
Not sure if ENV variables are required but I will try it out and let you know...

**Comment by mubarakone** [comment]
Sorry for the wait... issue fixed. It was noob mistake on my end, nothing wrong with you. I want to get this Frame out to the public quickly, so expect more of this haha 😅
