### ISSUE TITLE
Bug: Framegear shows frames with tx buttons as valid when missing the target and post_url for a tx button

### ISSUE THREAD

**Issue by briandoyle81CB** [coinbase/onchainkit#362]
### Describe the bug and the steps to reproduce it

1. Create a new frame 
2. Add a Button with a label
3. Give the button an action of `tx`
4. Do NOT add a target or post_url to the button
5. DO add a post_url to the frame

Framegear will show the frame as valid.

Deploy and test on the validator.

Observe the error: Not a valid target on the button

### What's the expected behavior?

Framegear should report an error if a tx button doesn't have a valid target or post_url, even if it can't test the tx itself.

**Comment by cpcramer** [comment]
Frames have been deprecated.
