### ISSUE TITLE
Bug: Framegear:  Getting `Unexpected end of JSON input` error with a button `target` and when there is no frame `postUrl`

### ISSUE THREAD

**Issue by nolanjannotta** [coinbase/onchainkit#380]
### Describe the bug and the steps to reproduce it

when a button has a `target` property AND when the frame does _not_ have a `postUrl` property, Framegear will throw a  `Uncaught (in promise) SyntaxError: Unexpected end of JSON input` error in the browser console. In the server console you get `TypeError: Cannot read properties of undefined (reading 'toString')` and ` POST /api/postFrame 500` 

to reproduce:
1. clone [a frame in 100 lines](https://github.com/Zizzamia/a-frame-in-100-lines)
2. in `app/page.tsx` delete the ``` postUrl: `${NEXT_PUBLIC_URL}/api/frame`,``` and add a `target` to the first button like this: ```{
      label: 'Story time',
      target: `${NEXT_PUBLIC_URL}/api/frame`,
    },```
3. run framegear and the frame server, paste url in framegear, press the button
4. you should see the same errors

I _believe_  it has something to do framegear/app/api/postFrame/route.ts. If I hardcode the url in this line: `const postUrl = frameData.url;` so like this: `const postUrl = "http://localhost:3000/api/frame" ` there is no error. So frameData.url is undefined. In a previous version of framegear that I cloned months ago (I'm not sure which version) I did not have this issue. I updated everything the other day and I started getting this error. 

Note: if you delete  the `const { isValid, message } = await getFrameMessage()` line and everything that uses `isValid` and `message` the frame will work in the frames.js debugger with the button `target`. So it seems like a framegear issue.

### What's the expected behavior?

Framegear should not throw an error and a button click with a target should work.

### What version of the libraries are you using?

onchainkit -  0.14.1
most recent framegear

**Comment by dudany** [comment]
I encountered the same issue with framegear

**Comment by cpcramer** [comment]
Frames have been deprecated.
