### ISSUE TITLE
Bug: no such file or directory: onchainkit/framegear

### ISSUE THREAD

**Issue by Olanetsoft** [coinbase/onchainkit#393]
### Describe the bug and the steps to reproduce it

After installing the project locally, the docs recommended the following steps:

```
cd onchainkit/framegear
npm install
npm run dev
```

But running `cd onchainkit/framegear` returns error:
```
no such file or directory: onchainkit/framegear
```

### What's the expected behavior?

The docs need to be updated to `cd framegear`, not `cd onchainkit/framegear`

### What version of the libraries are you using?

0.17.2

**Comment by Zizzamia** [comment]
Great point! Thank you for pointing that out.

**Comment by Olanetsoft** [comment]
> Did you `cd` into `onchainkit` after cloning? Because if that is the case the `cd onchainkit/framegear` will not work.
> 
> I just tried to clone than repo, and than do `cd onchainkit/framegear` and it did worked.
> 
> The docs are correct if followed as mentioned.
> 
> Which is:
> 
> 1. clone the repo by doing `git clone https://github.com/coinbase/onchainkit.git`
> 2. cd into the framegear folder `cd onchainkit/framegear`
> 3. install framegear dependencies ....

Got it. Thank you!
