### ISSUE TITLE
Feature Request: getFrameMetadata should return a whole NextJS Metadata object with OG tags filled

### ISSUE THREAD

**Issue by cnasc** [coinbase/onchainkit#44]
### Describe the solution you'd like

Frames don't work if full OG tags aren't there, by returning a full Metadata object for the user to export we can make our code a bit more error-proof.

Saw this bite someone earlier today, and they were confused why the function didn't result in an object that just worked.

**Comment by Zizzamia** [comment]
Solved with `v0.6.1`
