### ISSUE TITLE
Feature Request: Local Embed for Farcaster Frame Development

### ISSUE THREAD

**Issue by robpolak** [coinbase/onchainkit#53]
### Describe the solution you'd like

Developing Farcaster frame locally is a pain and typically requires users to push their changes to production to test.  It would be nice to create:

1. Lightweight emulator that follows the Farcaster OpenGraph spec
2. Create a web interface which allows you to test and debug frames locally.

**Comment by Zizzamia** [comment]
@cnasc and @taycaldwell will have something to share on this soon.

**Comment by JollyGrin** [comment]
Would it be possible to use (with credit) to frame.js' debugger? Seems like simplest-frame is also using this https://github.com/coinbase/onchainkit/issues/53

**Comment by Zizzamia** [comment]
@JollyGrin, spoiler alert :D 
@cnasc is working on a Frame playground as we speak.

**Comment by cnasc** [comment]
I think with the addition of `framegear` we can close this one and just use #146 to keep track of features (or create new issues if we have enough detail)
