### ISSUE TITLE
Bug: Mobile View Navigation and Overflow Problems

### ISSUE THREAD

**Issue by adarshswaminath** [coinbase/onchainkit#535]
### Describe the bug and the steps to reproduce it

I recently visited the onchainkit.xyz documentation website, which is a great resource for React components and TypeScript utilities to help build top-tier onchain apps. However, I noticed some issues with the mobile view that affect the user experience

**1.Navigation Bar Information Loss:**
 - In the desktop view, the navigation bar includes the logo, search bar, Docs, Onchain App Examples, Frame Examples, and version information.
 - In the mobile view, the navigation bar only displays the logo, Docs, a search icon, and GitHub logo links.
 - This significant reduction in available navigation options can make it difficult for users to access important sections of the documentation on mobile devices.
 
**2.Horizontal Overflow Issues:**
- On mobile devices, the page has horizontal overflow issues causing the content to extend beyond the visible screen width, resulting in a poor scrolling experience.

### *Screenshots:*
- **Desktop View Navigation Bar**
![image](https://github.com/coinbase/onchainkit/assets/69946307/99e5b709-213a-4b56-970a-54e2c6cefafd)
- **Mobile View Navigation Bar**
![image](https://github.com/coinbase/onchainkit/assets/69946307/697375bd-36c9-45b3-a41b-a07085664436)
- **Horizontal Overflow Issue**
![image](https://github.com/coinbase/onchainkit/assets/69946307/4db024b0-0036-4b34-a7ad-7748cdd9ecdd)

**Note**
I am not sure if this is the right place to report these issues, but I hope this feedback is helpful. The documentation site is a valuable resource, and improving the mobile experience will make it even more accessible to users on the go.

Thank you for looking into these issues.

**Comment by kyhyco** [comment]
Addressing this soon. Thanks for the report!

**Comment by Zizzamia** [comment]
Not my best CSS PR, but it should be fixed now.
