### ISSUE TITLE
Bug: type declarations not available have to use @coinbase/onchainkit/esm/*

### ISSUE THREAD

**Issue by blmalone** [coinbase/onchainkit#695]
### Describe the bug and the steps to reproduce it

When importing `ConnectAccount`:

```typescript
import { ConnectAccount } from '@coinbase/onchainkit/wallet';
```

I get the following error:

```sh
Cannot find module '@coinbase/onchainkit/wallet' or its corresponding type declarations.ts(2307)
```

---
Below is a screenshot of the error:

<img width="953" alt="Screenshot 2024-06-24 at 13 40 14" src="https://github.com/coinbase/onchainkit/assets/15608778/d0167094-b816-47dc-a599-d41f65c3479d">

---
Below is a screenshot when the error is resolved:
<img width="551" alt="Screenshot 2024-06-24 at 13 42 39" src="https://github.com/coinbase/onchainkit/assets/15608778/26974ea0-5df3-4c37-813b-98fac69b44eb">

---

Fix: I had to directly use `esm` in my import statement.

### What's the expected behavior?

Shouldn't have to use `esm` import. Or if I do, this should require a documentation update on your end.

### What version of the libraries are you using?

^0.22.2

**Comment by kyhyco** [comment]
It should work as `@coinbase/onchainkit/wallet`.

I can't reproduce this issue on [the sample app](https://github.com/Zizzamia/an-onchain-app-in-100-components).

Could you show me your tsconfig?

**Comment by kyhyco** [comment]
That is to say, we only build for `esm` so let's make sure that your tsconfig is correct. Will update the docs afterwards.

**Comment by kyhyco** [comment]
FYI we are updating `@coinbase/onchainkit/wallet` as we speak. It doesn't work that great as-is.

**Comment by kyhyco** [comment]
Here is a sneak peak at what we are cooking up!

<img width="271" alt="Screenshot 2024-06-24 at 9 06 06 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/fde87801-de73-4fa3-bc75-e576eba5abae">

**Comment by blmalone** [comment]
@kyhyco Those updates look cool. 
Here's my `tsconfig.ts`:


```json
{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "lib": ["dom", "es2017"],
    "jsx": "react",
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "include": ["src"]
}
```

**Comment by kyhyco** [comment]
could you try with these? 
```
{
  "compilerOptions": {
    // ...
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    // ...
  }
}
```

**Comment by blmalone** [comment]
Getting the same error:

<img width="531" alt="Screenshot 2024-06-25 at 19 17 41" src="https://github.com/coinbase/onchainkit/assets/15608778/d8e14dcf-8cf7-41b3-83b8-396e9e6662f9">

**Comment by blmalone** [comment]
@kyhyco here's the repo I'm working with: https://github.com/blmalone/cafebabe

**Comment by kyhyco** [comment]
In middle of making the new ConnectWallet component. I will take a look at this after I make some progress on the new component!

**Comment by kyhyco** [comment]
Aight try this:
```
{
  "compilerOptions": {
    "target": "ES2020",
    "lib": ["DOM", "DOM.Iterable", "esnext"],
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "useDefineForClassFields": true
  },
  "include": ["src"]
}
```

**Comment by kyhyco** [comment]
Also tell Nick I said Hi

**Comment by blmalone** [comment]
Thanks for the reply. I tried your suggestion and I'm getting:

```
🚨 Build failed.

@parcel/core: Failed to resolve '@coinbase/onchainkit/identity' from './src/components/Home.tsx'

  /Users/blaine/code/cafebabe/web/src/components/Home.tsx:22:33
    21 | import { ConnectAccount } from "@coinbase/onchainkit/wallet";
  > 22 | import { Avatar, Address } from "@coinbase/onchainkit/identity";
  >    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    23 | import {
    24 |   useAccount,
    ```

**Comment by kyhyco** [comment]
Ah can't help you there. Don't know how parcel works.

**Comment by kyhyco** [comment]
@blmalone I recommend this though https://tailwindcss.com/docs/guides/vite

Make a new project using that guide which will setup vite (parcel alternative) for you out of the box.

Follow, onchainkit installation instructions and copy all the files from the old project into this new one.
