### ISSUE TITLE
Bug: [Avatar] - className overrides not working as expected

### ISSUE THREAD

**Issue by sergical** [coinbase/onchainkit#696]
### Describe the bug and the steps to reproduce it

adding `className="h-4 w-4 mr-2"` doesn't update the default 32x32 svg

### What's the expected behavior?

The avatar circle becomes smaller

**Comment by kyhyco** [comment]
What's good buddy. Fix coming right up

**Comment by sergical** [comment]
> What's good buddy. Fix coming right up

My brother 🤍

**Comment by kyhyco** [comment]
Are you intending to use attestation badge with the small Avatar? 

This only fixes the className override and **does not** handle Badge sizing _if_ you do something like this
```
<Avatar className="h-4 w-4 mr-2">
  <Badge />
</Avatar>
```

**Comment by sergical** [comment]
Wasn't planning on it, but shouldn't Badge be able to consume a className as well? just thinking out loud here, no clue how it's set up 😅

**Comment by kyhyco** [comment]
Working on a system that will allow you to override the entire presentation layer. Not there yet though!

**Comment by kyhyco** [comment]
Cutting a new release. One sec.

**Comment by sergical** [comment]
I got a bit of a problem bumping versions from 0.16 to past 20 now with wagmi too btw 😅 

im using wagmi provider from privy but onchain provider complains that it doesn't see it

context: https://docs.privy.io/guide/react/wallets/usage/wagmi

Also theres a typescript mismatch with a viem version im using vs latest onchainkit viem version where chain is incompatible. 

i can submit those 2 separately though.

thank you for building 🤍

**Comment by kyhyco** [comment]
Could you open up a new issue? Let's discuss it there. 1 issue for those would be great.

**Comment by kyhyco** [comment]
Aight try out 0.22.3 to fix the avatar className override bug

**Comment by sergical** [comment]
Okay ill update and open up an issue for the other ones with the repo so it's contextual, thank you so much Ky!
