### ISSUE TITLE
Feature Request: add "Add Funds" to wallet dropdown

### ISSUE THREAD

**Issue by fakepixels** [coinbase/onchainkit#742]
### Describe the solution you'd like

Add a new option to the wallet dropdown called "Add Funds" to provide users with an easy way to fund their smart wallet.

Place this new component within the WalletDropdown component, ideally positioned above the WalletDropdownDisconnect option. When clicked, this option should initiate a process to add funds to the user's smart wallet.

**Comment by Zizzamia** [comment]
Initial version built with the `<WalletDropdownFundLink />` component.

https://onchainkit.xyz/wallet/wallet-dropdown-fund-link
