### ISSUE TITLE
Feature Request: getFrameMessage() should include inputText

### ISSUE THREAD

**Issue by alfonso-paella** [coinbase/onchainkit#76]
### Describe the solution you'd like

The decoded, validated payload right now contains button clicks, but not the input text if any

Right now the workaround is to obtain it from the unsigned payload, thus is subject to data integrity attacks

**Comment by Zizzamia** [comment]
Great point! Let me fix that right away!

**Comment by Zizzamia** [comment]
@alfonso-paella is fixed with `v0.4.4`.

Now you can just get the input text from `message.input`.

**Comment by alfonso-paella** [comment]
🐐 GOAT
