### ISSUE TITLE
Feature Request: Migrate to Vitest

### ISSUE THREAD

**Issue by roushou** [coinbase/onchainkit#760]
### Describe the solution you'd like

Running unit tests with Jest currently makes my machine (Arch / 16GB ram) goes OOM while going quickly with [Vitest](https://vitest.dev/). Both API are similar. Looking for your experience @kyhyco @Zizzamia. Maybe I'm an isolated case so it may not be worth the effort.

**Comment by Zizzamia** [comment]
@roushou, my only hesitation is around having hard time to write Mock test or general less experience with those tests. And how well Github Co-Pilot can code with Vitest.

BUT, if those conditions are met, and the transition is super smooth. I am all for it.

@roushou is it something you can help us with?

Also, we do a lot of things with `yarn` around OnchainKit, I feel ready for us to migrate to `bun` as well.

**Comment by roushou** [comment]
I can help with both.

To give some insight with Bun. Things are fast, intuitive and I haven't had any major issue yet but I also mainly develop apps and don't really touch runtime stuff. But I remember having a few issues when using packages that relied on Node.js runtime stuff not supported by Bun.

In the context of OnchainKit, I think it can replace Yarn with no issues. Maybe for bundling to `esm` too (cjs/iife are [not supported](https://bun.sh/docs/bundler#format) yet) but I don't how it behaves regarding `"use client"` directives https://github.com/coinbase/onchainkit/pull/691. I haven't tried Bun tests yet.

Regarding Vitest, this is pretty much like Jest with a similar API, environments (node, jsdom, ...) with a few adjustments. There's a migration guide [here](https://vitest.dev/guide/migration.html#migrating-from-jest). No idea about Copilot since I don't use it. IMO someone familiar with Jest should not have any issues with Vitest.

**Comment by Zizzamia** [comment]
https://github.com/orgs/community/discussions/62769 🤔

I wonder if Vitest is now supported by CoPilot.

**Comment by roushou** [comment]
Best way to know is to try it. I don't have Copilot though

**Comment by Zizzamia** [comment]
Done :-)

We are with Vitest.

**Comment by roushou** [comment]
Amazing!
