### ISSUE TITLE
Feature Request: Export FrameMetadata type

### ISSUE THREAD

**Issue by alfonso-paella** [coinbase/onchainkit#82]
### Describe the solution you'd like

The SDK exports a FrameMetadata object which is a React component.

There's a second thing with the same name in the SDK: the [`FrameMetadata` type](https://github.com/coinbase/onchainkit/blob/main/src/core/types.ts#L70). 

It would be useful to be able to use this type, as it's the type we must pass to `getFrameHtmlResponse()`

If it is indeed exposed, I'd consider renaming it so there's no clash with the FrameMetadata component

**Comment by Zizzamia** [comment]
Love that you discovered the `FrameMetadata` component even if I still have to document it. 👏

I agree with you on both exporting and renaming. Should it just be `FrameMetadataType`? or do you have any other idea as name?

**Comment by alfonso-paella** [comment]
nah that name sounds great

**Comment by Zizzamia** [comment]
@alfonso-paella `v0.4.5` is out with the `FrameMetadataType`, have fun!
