### ISSUE TITLE
Bug: TypeScript Error in Frames 101 Example

### ISSUE THREAD

**Issue by RobertDoc** [coinbase/onchainkit#975]
### Describe the bug and the steps to reproduce it

1. Fork https://github.com/Zizzamia/a-frame-in-100-lines
2. Update OnchainKit to 0.27.0 in package.json.
3. TS error in page.tsx:

TS1479: The current file is a CommonJS module whose imports will produce require calls; however, the referenced file is an ECMAScript module and cannot be imported with require. Consider writing a dynamic import(@coinbase/onchainkit/frame)' call instead.

### What's the expected behavior?

No TS error.

### What version of the libraries are you using?

- OnchainKit 0.27.0

**Comment by Zizzamia** [comment]
Try the latest https://github.com/Zizzamia/a-frame-in-100-lines, it should be fixed now.

And thank you again for taking the time to report this.

**Comment by Bartletti** [comment]
@wawrzy17

**Comment by Zizzamia** [comment]
Closing this, as it seems resolved.
